version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Entered the build phase...
      - mvn package
      - echo Packaged successfully...
      - sam package
        --template-file sam-template.yml
        --s3-bucket codepipeline-us-east-1-547338236821
        --output-template-file packaged-template.yml
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - packaged-template.yml
