Transform: AWS::Serverless-2016-10-31
Description: >
    Sample SAM Template for food delivery app

Globals:
    Function:
        Timeout: 20

Resources:

    FoodDeliveryFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .target/SearchRestaurant-1.0-SNAPSHOT-shaded.jar
            Handler: org.example.Main::buyFood
            Runtime: java11

            Events:
                searchRestaurant:
                    Type: Api
                    Properties:
                        Path: /
                        Method: get
